apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: RUNNER_NAME
          value: "minikube-runner"
        - name: REPO_URL
          value: "HuseyinBeller/book-review-app"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: RUNNER_TOKEN
        - name: RUNNER_WORKDIR
          value: "/tmp/github-runner"
        - name: ORG_RUNNER
          value: "false"
        - name: LABELS
          value: "minikube"
        - name: RUNNER_GROUP
          value: "Default"
