apiVersion: v1
kind: Namespace
metadata:
  name: github-runner
---
apiVersion: v1
kind: Secret
metadata:
  name: github-runner-secret
  namespace: github-runner
type: Opaque
stringData:
  RUNNER_TOKEN: "ASSLE2G7AV6BBZ5RQSYJANTINE5NO"  # Replace this with your actual token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: runner
        image: summerwind/actions-runner:latest
        env:
        - name: RUNNER_NAME
          value: "minikube-runner"
        - name: RUNNER_REPO
          value: "HuseyinBeller/book-review-app"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: RUNNER_TOKEN
        - name: RUNNER_WORKDIR
          value: "/runner"
        - name: RUNNER_GROUP
          value: "Default"
        - name: RUNNER_LABELS
          value: "minikube"
        volumeMounts:
        - mountPath: /runner
          name: runner-workdir
      volumes:
      - name: runner-workdir
        emptyDir: {}

