{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "book-review.fullname" . }}-frontend-nginx-config
  labels:
    {{- include "book-review.frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html index.htm;

        # Serve static files
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxy API calls to backend service
        location /api/ {
            proxy_pass http://{{ include "book-review.fullname" . }}-backend:{{ .Values.backend.service.port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
{{- end }} 