apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book-review-app
  namespace: argocd
spec:
  project: default  ##
  source:
    repoURL: https://github.com/HuseyinBeller/book-review-app.git
    targetRevision: HEAD
    path: book-review-app/manifests/base
  destination:
    server: https://kubernetes.default.svc
    namespace: book-review
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
